{
  "id":103,
  "name":"migxcartimages",
  "formtabs":[
    {
      "MIGX_id":1,
      "caption":"Image",
      "print_before_tabs":"0",
      "fields":[
        {
          "MIGX_id":1,
          "field":"title",
          "caption":"Title",
          "description":"",
          "description_is_code":"0",
          "inputTV":"",
          "inputTVtype":"",
          "configs":"",
          "sourceFrom":"config",
          "sources":"[]",
          "inputOptionValues":"",
          "default":""
        },
        {
          "MIGX_id":2,
          "field":"description",
          "caption":"Description",
          "description":"",
          "description_is_code":"0",
          "inputTV":"",
          "inputTVtype":"",
          "configs":"",
          "sourceFrom":"config",
          "sources":"[]",
          "inputOptionValues":"",
          "default":""
        }
      ]
    }
  ],
  "contextmenus":"",
  "actionbuttons":"upload",
  "columnbuttons":"update",
  "filters":"[]",
  "extended":{
    "migx_add":"",
    "formcaption":"",
    "update_win_title":"",
    "win_id":"migxcartimages",
    "maxRecords":"",
    "multiple_formtabs":"",
    "extrahandlers":"this.handlePositionSelector||this.publishObject||this.unpublishObject",
    "packageName":"migxcart",
    "classname":"mcProductImage",
    "task":"",
    "getlistsort":"pos",
    "getlistsortdir":"",
    "use_custom_prefix":"0",
    "prefix":"",
    "grid":"",
    "gridload_mode":2,
    "check_resid":1,
    "check_resid_TV":"",
    "join_alias":"Product",
    "has_jointable":"yes",
    "getlistwhere":"",
    "joins":"",
    "cmpmaincaption":"",
    "cmptabcaption":"",
    "cmptabdescription":"",
    "cmptabcontroller":"",
    "winbuttons":"",
    "onsubmitsuccess":"",
    "submitparams":""
  },
  "columns":[
    {
      "MIGX_id":1,
      "header":"ID",
      "dataIndex":"id",
      "width":10,
      "sortable":"false",
      "show_in_grid":1,
      "renderer":"",
      "clickaction":"",
      "selectorconfig":"",
      "renderoptions":"[]"
    },
    {
      "MIGX_id":2,
      "header":"Filename",
      "dataIndex":"filename",
      "width":20,
      "sortable":"false",
      "show_in_grid":1,
      "renderer":"this.renderChunk",
      "clickaction":"",
      "selectorconfig":"",
      "renderoptions":[
        {
          "MIGX_id":1,
          "name":"renderImageColumn",
          "value":"",
          "clickaction":"",
          "handler":"",
          "image":""
        }
      ]
    },
    {
      "MIGX_id":3,
      "header":"Position",
      "dataIndex":"pos",
      "width":10,
      "sortable":"false",
      "show_in_grid":1,
      "renderer":"this.renderPositionSelector",
      "clickaction":"",
      "selectorconfig":"",
      "renderoptions":"[]"
    },
    {
      "MIGX_id":4,
      "header":"Title",
      "dataIndex":"title",
      "width":20,
      "sortable":"false",
      "show_in_grid":1,
      "renderer":"this.renderRowActions",
      "clickaction":"",
      "selectorconfig":"",
      "renderoptions":"[]"
    },
    {
      "MIGX_id":5,
      "header":"Published",
      "dataIndex":"published",
      "width":10,
      "sortable":"false",
      "show_in_grid":1,
      "renderer":"this.renderClickCrossTick",
      "clickaction":"",
      "selectorconfig":"",
      "renderoptions":"[]"
    }
  ],
  "createdby":1,
  "createdon":"2013-06-26 18:43:24",
  "editedby":1,
  "editedon":"2013-06-27 09:11:34",
  "deleted":0,
  "deletedon":"-1-11-30 00:00:00",
  "deletedby":0,
  "published":1,
  "publishedon":"2013-06-26 01:00:00",
  "publishedby":0
}